### ISSUE TITLE
Add a "take a break" / "do some stretches" timer

### ISSUE THREAD

**Issue by tinnet** [burningtreeio/screenRDA#12]

**Comment by michaelcontento** [comment]
Wie wäre es, wenn man mit einer API (wie auch immer), mit screenRDA kommunizieren könnte? Dann könnte man solch ein Feature auslagern. 

Grundsätzlich würde ich screenRDA möglichst simple und klein (sowohl UI als auch Ressourcen) halten. Im best-case könnte man den aktuellen update-timer von 5min auch auf "dann, wenn sich das Icon ändern würde" umstellen. 

Also schließen? Bzw. Title ändern auf "API erfinden"?

**Comment by tinnet** [comment]
also meine tendenz wäre auch pro API, aber ich frage mich, was denn am ende weniger "simple und klein" von ressourcen her wäre, screenRDA mit strechttimer oder 2 binaries? Und wenn der stretchtimer schon ne seperate binary ist, kann man ja auch auf die API pfeifen und selber die zeit messen?!

**Comment by michaelcontento** [comment]
Ja, stimmt! Wieso muss / sollte der stretchtimer überhaupt an screenRDA gekoppelt sein? Was wäre der Vorteil?

**Comment by tinnet** [comment]
eine binary weniger, ein feature mehr für screenRDA

**Comment by michaelcontento** [comment]
Featuritis? 😂

**Comment by tinnet** [comment]
zweites program = nochmal 4mb ram weg, das feature in screenRDA = kaum mehr ram

also von der ressourcenseite gewinnt stretchtimer einbauen

von der "scope klein halten" seite gewinnt seperate binary

**Comment by tinnet** [comment]
ich glaub ich würd's seperat bauen.. oder ein pluginsystem erfinden (das ist bestimmt total nicht kompliziert!!111eins)

**Comment by michaelcontento** [comment]
ich würde es auch seperat bauen. ehrlich gesagt finde ich auch ne API für screenRDA erfinden schon .. puh .. also sehr nice-to-have und vermutlich nichts wofür ich zeit aufbringen würde (außer mir ist mal wirklich sehr langweilig und ich hab speziell auf so ein feature lust).

**Comment by tinnet** [comment]
darum ist das issue ja in "future" ;) ist ja nur dein verlangen hier die issue liste kleiner zu machen das dich hier reintreibt

**Comment by michaelcontento** [comment]
bingo 😁

**Comment by tinnet** [comment]
und wie ich dich kenne ist "offen lassen in future" eh keine option und du diskutierst das feature hier eh weg ;)
